### ISSUE TITLE
Drop Raspbian in Favor of Rasperry Pi OS

### ISSUE THREAD

**Issue by oxzi** [Icinga/package-installation-docs#3]
AFAIK, we're not building packages for Raspbian anymore - at least for new packages. Thus, the Raspbian.md file might be removed.

Furthermore, it should be considered removing the current packages or moving them to another location as otherwise the user's package manager says everything is up to date while the packages are getting outdated.

**Comment by lippserd** [comment]
Since we also list Rasperry Pi OS on packages.icinga.com, we should add this here and also mention that Debian packages are used, while only 64-bit packages are available.

**Comment by yhabteab** [comment]
Fixed by #7!

Can't close it, so please close!
